'use strict';
const D=window.POINT_DATA, periods=D.periods.sort((a,b)=>a.key.localeCompare(b.key));
const money=n=>n==null?'Não informado':n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), pct=n=>n==null?'—':`${n>0?'+':''}${(n*100).toFixed(1).replace('.',',')}%`, esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const monthName=m=>new Date(2026,m-1,1).toLocaleString('pt-BR',{month:'long'}), label=p=>`${p.half}ª quinzena · ${monthName(p.month)} ${p.year}`, date=(y,m,d)=>`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`, diff=(a,b)=>Math.round((Date.parse(b)-Date.parse(a))/86400000)+1;
const bounds=p=>[date(p.year,p.month,p.half===1?1:16),date(p.year,p.month,p.half===1?15:new Date(p.year,p.month,0).getDate())];
const registry=new Map(D.registry.map(r=>[String(r.pdv_id),r])), terminals=new Map(D.terminals.map(r=>[String(r.ponto),String(r.pdv_id)]));
function stores(ps){const map=new Map();for(const p of ps)for(const row of p.points){const id=terminals.get(row.point)||D.nameMatches?.[row.name]||`name:${row.name}`,r=registry.get(id);if(r?.include===false)continue;if(!map.has(id))map.set(id,{id,name:row.name,revenue:0,registry:r,city:row.city});map.get(id).revenue+=row.revenue;}const days=ps.reduce((s,p)=>{const [a,b]=bounds(p);return s+diff(a,b)},0);for(const r of map.values()){r.days=r.registry?.inauguracao?ps.reduce((s,p)=>{let[a,b]=bounds(p);a=a>r.registry.inauguracao?a:r.registry.inauguracao;b=r.registry.encerramento&&r.registry.encerramento<b?r.registry.encerramento:b;return s+Math.max(0,diff(a,b))},0):days;r.daily=r.days?r.revenue/r.days:null;r.perApartment=r.registry?.apartamentos>0?r.revenue/r.registry.apartamentos:null;}return [...map.values()].sort((a,b)=>b.revenue-a.revenue||a.name.localeCompare(b.name));}
function previous(p){let y=p.year,m=p.month,h=1;if(p.half===1){h=2;m--;if(!m){m=12;y--;}}return periods.find(q=>q.year===y&&q.month===m&&q.half===h);}
function comparison(p){const prev=previous(p),old=new Map((prev?stores([prev]):[]).map(r=>[r.id,r]));return stores([p]).map(r=>{const before=old.get(r.id);r.change=before?.daily>0&&r.daily!=null?r.daily/before.daily-1:null;const opening=r.registry?.inauguracao;r.eligible=opening?opening<bounds(p)[0]:null;r.alert=r.eligible===true&&r.change<-.2&&r.change!=null;r.candidate=r.eligible===null&&r.change<-.2&&r.change!=null;return r;});}
let mode="monthly";
let selected=periods.length-1,page=0,paused=false,elapsed=0,seconds=20,slides=[];
const periodSelect=document.querySelector('#period');
function monthPeriods(p){return periods.filter(q=>q.year===p.year&&q.month===p.month);}
function setOptions(){const current=periods[selected];const choices=mode==='monthly'?periods.filter((p,i)=>!periods[i+1]||periods[i+1].month!==p.month||periods[i+1].year!==p.year):periods;if(mode==='monthly')selected=periods.indexOf(monthPeriods(current).at(-1));periodSelect.innerHTML=choices.map(p=>`<option value="${periods.indexOf(p)}">${esc(mode==='monthly'?`${monthName(p.month)} ${p.year}${monthPeriods(p).length<2?' · parcial':''}`:label(p))}</option>`).join('');periodSelect.value=selected;}
setOptions();
function monthlyHistory(p){return `<h2>Faturamento por mês</h2><div class="monthly-totals">${periods.filter((q,i)=>(!periods[i+1]||periods[i+1].month!==q.month||periods[i+1].year!==q.year)&&q.key<=monthPeriods(p).at(-1).key).map(q=>{const ps=monthPeriods(q),m=metrics(ps);return `<div class="month-total"><strong>${monthName(q.month)} ${q.year}</strong><div class="value">${money(m.total)}</div><small>${ps.length<2?'Parcial · ':''}${m.days} dias · ${money(m.total/m.days)}/dia</small></div>`}).join('')}</div>`;}
function heading(kicker,title,sub){return `<div class="eyebrow">${kicker}</div><h1>${title}</h1><p class="sub">${sub}</p>`;}
function includedUnits(){return (D.control||[]).filter(r=>r.include);}
function openingsBetween(start,end){const units=includedUnits(),known=units.filter(r=>r.inauguracao),missing=units.filter(r=>!r.inauguracao&&r.status!=='Em Implantação').length;return {count:known.filter(r=>r.inauguracao>=start&&r.inauguracao<=end).length,known:known.length,missing,available:known.length>0||missing===0};}
function metrics(ps){const rows=stores(ps),total=rows.reduce((s,r)=>s+r.revenue,0),days=ps.reduce((s,p)=>s+diff(...bounds(p)),0),start=bounds(ps[0])[0],end=bounds(ps.at(-1))[1],o=openingsBetween(start,end);return {rows,total,days,opened:o.available?o.count:null,openingMissing:o.missing,active:includedUnits().filter(r=>r.status==='Em Operação').length,complete:rows.every(r=>r.registry?.inauguracao)};}
function openingsChart(){const units=includedUnits(),keys=[...new Set([...periods.map(p=>`${p.year}-${String(p.month).padStart(2,'0')}`),...units.filter(r=>r.inauguracao).map(r=>r.inauguracao.slice(0,7))])].sort();const values=keys.map(key=>({key,...openingsBetween(key+'-01',key+'-31')})),max=Math.max(1,...values.map(r=>r.count));return heading('Expansão da rede','Inaugurações por mês','Datas reais de inauguração')+`<div class="implementation-count"><span>Lojas em implantação</span><strong>${implantations().length}</strong></div><div class="panel"><div class="opening-columns">${values.map(r=>`<div class="opening-column"><strong>${r.available?r.count:'—'}</strong><div class="column-track">${r.available?`<i style="height:${r.count/max*100}%"></i>`:'<span>Sem datas</span>'}</div><label>${monthName(Number(r.key.slice(5)))} ${r.key.slice(0,4)}</label></div>`).join('')}</div></div><p class="notice">${values[0]?.missing?`${values[0].missing} unidades fora de implantação ainda sem data de inauguração. ${values.some(r=>r.known)?'As colunas mostram somente datas informadas; a contagem é parcial.':'Preencha as datas na Base de licenciados para formar as colunas. Ausência de informação não significa zero inaugurações.'}`:'Contagem conforme datas registradas na Base de licenciados.'}</p>`;}
function summary(ps,monthly=false){const m=metrics(ps),p=ps.at(-1),partial=monthly&&ps.length<2,prev=previous(p),prevM=prev?metrics([prev]):null,change=!monthly&&prevM?.total>0?m.total/m.days/(prevM.total/prevM.days)-1:null;const title=monthly?`${monthName(p.month)} ${p.year}${partial?' · parcial':''}`:label(p);const gap=ps.reduce((s,p)=>s+p.products.reduce((a,r)=>a+r.revenue,0)-p.points.reduce((a,r)=>a+r.revenue,0),0);return heading(monthly?'Consolidado mensal':'Visão quinzenal',title,`${m.days} dias cobertos${partial?' · apenas a quinzena disponível':''} · ${m.rows.length} PDVs com vendas no período`)+`<div class="cards"><div class="card"><label>Faturamento da rede</label><div class="value">${money(m.total)}</div><p class="small">${monthly?'Soma das quinzenas disponíveis':'Total do período'}</p></div><div class="card"><label>Média diária</label><div class="value">${money(m.total/m.days)}</div><p class="small">${change==null?'':`${pct(change)} vs. quinzena anterior`}</p></div><div class="card"><label>Lojas ativas</label><div class="value">${m.active}</div></div><div class="card"><label>Inaugurações</label><div class="value">${m.opened??'—'}</div><p class="small">${m.opened==null?'Datas não informadas':m.openingMissing?'Parcial · faltam datas':'No período'}</p></div></div><div class="split"><div class="panel">${monthly?monthlyHistory(p):`<h2>Média diária da rede</h2><div class="bars">${periods.slice(0,selected+1).map(q=>{const n=metrics([q]),v=n.total/n.days;return `<div class="bar"><b>${money(v)}</b><i style="height:${v/3000*130}px"></i>${q.half}ª · ${String(q.month).padStart(2,'0')}</div>`}).join('')}</div>`}</div><div class="panel"><h2>Líder do período</h2><div class="eyebrow">🥇 ${esc(m.rows[0]?.name||'Sem dados')}</div><div class="value">${money(m.rows[0]?.revenue)}</div></div></div>${Math.abs(gap)>.01?`<div class="notice">Conferência pendente: produtos superam o faturamento em ${money(gap)} neste período.</div>`:''}`;}
const tvRows=()=>window.innerHeight<=700?5:window.innerHeight<=900?6:10;
const implantationRows=()=>Math.min(7,tvRows());
function ranking(ps,offset,monthly){const p=ps.at(-1),m=metrics(ps),comparisons=new Map(comparison(p).map(r=>[r.id,r]));return heading(monthly?'Ranking mensal':'Ranking quinzenal',monthly?`${monthName(p.month)} ${p.year}${ps.length<2?' · parcial':''}`:label(p),monthly?'Ordem por faturamento consolidado':'Ordem por faturamento · variação calculada pela média diária')+`<div class="panel"><table><thead><tr><th>PDV</th><th>Faturamento</th><th>Média / dia</th>${monthly?'':'<th>Variação / dia</th>'}</tr></thead><tbody>${m.rows.slice(offset,offset+tvRows()).map((r,i)=>{const c=comparisons.get(r.id),rank=offset+i;return `<tr class="${!monthly&&c?.alert?'red':''}"><td><span class="rank">${['🥇','🥈','🥉'][rank]||rank+1}</span>${esc(r.name)}${!monthly&&c?.candidate?'<small>Queda >20% · inauguração não informada</small>':''}</td><td>${money(r.revenue)}</td><td>${money(r.daily)}</td>${monthly?'':`<td class="${c?.change<0?'negative':'positive'}">${pct(c?.change)}</td>`}</tr>`}).join('')}</tbody></table></div><p class="small">${offset+1}–${Math.min(offset+tvRows(),m.rows.length)} de ${m.rows.length} PDVs com vendas no período · Médias ajustadas pelas datas informadas, quando disponíveis.</p>`;}
function alerts(p){const rows=comparison(p).filter(r=>r.alert||r.candidate);return heading('Acompanhamento','Alertas de faturamento',`${label(p)} · queda superior a 20% na média diária`)+(rows.length?`<div class="list">${rows.map(r=>`<div class="panel ${r.alert?'red':''}"><div class="eyebrow">${r.alert?'Alerta confirmado':'Data de inauguração pendente'}</div><h2>${esc(r.name)}</h2><div class="value negative">${pct(r.change)}</div><p>Média diária: ${money(r.daily)}</p><p class="small">${r.alert?'Quinzena de inauguração já concluída.':'Queda identificada; falta confirmar elegibilidade pelo cadastro.'}</p></div>`).join('')}</div>`:'<div class="empty">Nenhuma queda superior a 20% nas lojas com comparação disponível.</div>')+'<p class="sub" style="margin-top:24px">A primeira quinzena de inauguração é isenta. Sem venda anterior ou com base zero, a variação não é calculada.</p>';}
function periodTitle(ps){const p=ps.at(-1);return mode==='monthly'?`${monthName(p.month)} ${p.year}${ps.length<2?' · parcial':''}`:label(p);}
function productTotals(ps){const map=new Map();for(const p of ps)for(const r of p.products){if(!map.has(r.id))map.set(r.id,{...r,revenue:0,quantity:0});const v=map.get(r.id);v.revenue+=r.revenue;v.quantity+=r.quantity;}return [...map.values()];}
function products(ps,by='revenue'){const rows=productTotals(ps),total=rows.reduce((s,r)=>s+r.revenue,0),quantity=rows.reduce((s,r)=>s+r.quantity,0);return heading('Vendas de produtos','Ranking de produtos',`${periodTitle(ps)} · ${by==='revenue'?'Ordenado por faturamento':'Ordenado por quantidade'} · ${money(total)} · ${quantity.toLocaleString('pt-BR')} unidades`)+`<div class="panel compact"><table><thead><tr><th>Produto</th><th>Unidades</th><th>Valor vendido</th></tr></thead><tbody>${rows.sort((a,b)=>b[by]-a[by]||a.name.localeCompare(b.name)).slice(0,tvRows()).map((r,i)=>`<tr><td><span class="rank">${['🥇','🥈','🥉'][i]||i+1}</span>${esc(r.name)}</td><td>${r.quantity.toLocaleString('pt-BR')}</td><td>${money(r.revenue)}</td></tr>`).join('')}</tbody></table></div><p class="small">Top ${Math.min(tvRows(),rows.length)} de ${rows.length} produtos · consolidado da rede, sem detalhamento por PDV.${Math.abs(total-metrics(ps).total)>.01?' Diferença entre P e V: '+money(total-metrics(ps).total)+'.':''}</p>`;}
function apartments(ps,offset=0){const rows=stores(ps),known=rows.filter(r=>r.perApartment!=null).sort((a,b)=>b.perApartment-a.perApartment||a.name.localeCompare(b.name));const apartmentRevenue=known.reduce((sum,r)=>sum+r.revenue,0),apartmentCount=known.reduce((sum,r)=>sum+r.registry.apartamentos,0);return heading('Ranking por apartamento','Ticket médio por apartamento',`${periodTitle(ps)} · faturamento do condomínio ÷ quantidade de apartamentos`)+`<div class="ticket-macro"><label>Ticket médio geral por apartamento</label><strong>${money(apartmentCount?apartmentRevenue/apartmentCount:null)}</strong><small>${known.length} condomínios · ${apartmentCount} apartamentos com vendas</small></div>`+(known.length?`<div class="panel compact"><table><thead><tr><th>PDV</th><th>Apartamentos</th><th>R$ / apartamento</th><th>R$ / apto / dia</th></tr></thead><tbody>${known.slice(offset,offset+tvRows()).map((r,i)=>`<tr><td><span class="rank">${['🥇','🥈','🥉'][offset+i]||offset+i+1}</span>${esc(r.name)}</td><td>${r.registry.apartamentos}</td><td>${money(r.perApartment)}</td><td>${money(r.daily==null?null:r.daily/r.registry.apartamentos)}</td></tr>`).join('')}</tbody></table></div><p class="small">${known.length} de ${rows.length} PDVs com apartamentos informados. Base de licenciados: vínculo pelos códigos dos terminais. ${rows.filter(r=>r.perApartment==null).map(r=>esc(r.name)).join(', ')}${known.length<rows.length?' fora do ranking por falta de quantidade.':''}</p>`:'<div class="empty">Nenhum PDV com apartamentos informados neste período.</div>');}
function implantations(){return includedUnits().filter(r=>r.status==='Em Implantação');}
const displayDate=d=>d?d.split('-').reverse().join('/'):'—';
function directory(offset=0){const rows=implantations();return heading('Expansão da rede','Implantações',`${rows.length} locais em implantação`)+`<div class="panel compact implementation-list"><table><thead><tr><th>Local</th><th>Cidade</th><th>Data do contrato</th><th>Previsão de inauguração</th></tr></thead><tbody>${rows.slice(offset,offset+implantationRows()).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.city)}</td><td>${displayDate(r.contractDate)}</td><td>${displayDate(r.expectedOpening)}</td></tr>`).join('')}</tbody></table></div><p class="small">${offset+1}–${Math.min(offset+implantationRows(),rows.length)} de ${rows.length} locais · — = data não informada.</p>`;}
function rebuild(){const p=periods[selected],ps=mode==='monthly'?monthPeriods(p):[p];slides=[()=>summary(ps,mode==='monthly')];for(let i=0;i<stores(ps).length;i+=tvRows())slides.push(()=>ranking(ps,i,mode==='monthly'));const count=stores(ps).filter(r=>r.perApartment!=null).length;for(let i=0;i<Math.max(1,count);i+=tvRows())slides.push(()=>apartments(ps,i));slides.push(()=>products(ps,elapsed>=seconds/2?'quantity':'revenue'),()=>openingsChart());for(let i=0;i<implantations().length;i+=implantationRows())slides.push(()=>directory(i));slides.push(()=>alerts(ps.at(-1)));page=0;elapsed=0;const chooser=document.querySelector('#screen');chooser.innerHTML=slides.map((fn,i)=>{const match=fn().match(/<h1>(.*?)<\/h1>/);return `<option value="${i}">${i+1}. ${match?match[1]:'Página'}</option>`}).join('');render();}
document.querySelector('#screen').onchange=e=>{page=Number(e.target.value);render();};
document.querySelector('#mode').onchange=e=>{mode=e.target.value;setOptions();rebuild();};
function render(reset=true){if(reset)elapsed=0;document.querySelector('#screen').value=page;document.querySelector('#view').innerHTML=slides[page]();document.querySelector('#page').textContent=`${page+1} / ${slides.length}`;document.querySelector('#meta').textContent=`POINT · Atualizado em ${new Date(D.updated).toLocaleString('pt-BR')} · ${paused?'Pausado':'Modo TV'}`;document.querySelector('#progress').style.width=`${elapsed/seconds*100}%`;}
function move(n){page=(page+n+slides.length)%slides.length;render();}document.querySelector('#next').onclick=()=>move(1);document.querySelector('#prev').onclick=()=>move(-1);periodSelect.onchange=()=>{selected=Number(periodSelect.value);rebuild();};document.querySelector('#duration').onchange=e=>{seconds=Number(e.target.value);render();};document.querySelector('#pause').onclick=()=>{paused=!paused;document.querySelector('#pause').textContent=paused?'Retomar':'Pausar';render(false);};document.querySelector('#full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{document.querySelector('#full').textContent='Use F11';}};document.addEventListener('keydown',e=>{if(['SELECT','INPUT'].includes(e.target.tagName))return;if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);if(e.code==='Space'){e.preventDefault();document.querySelector('#pause').click();}});setInterval(()=>{if(paused)return;const before=elapsed;elapsed+=.25;if(elapsed>=seconds)move(1);else if(before<seconds/2&&elapsed>=seconds/2)render(false);document.querySelector('#progress').style.width=`${elapsed/seconds*100}%`;},250);rebuild();
window.addEventListener("resize",()=>{clearTimeout(window.pointResizeTimer);window.pointResizeTimer=setTimeout(rebuild,250);});
